buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
	nixpkgsArchive = '4400a454f328c3f5a998ff0a29bb4c0afc890403'

[phases.install]
  cmds = ["npm install"] # changed

[phases.build]
  cmds = ["npm run build"] # changed
