// GENERATED by scripts/size-cli/run.ts — this baseline version is committed;
// the size script temporarily rewrites it per component and restores it after.
import { Component, provideZonelessChangeDetection } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

// __SIZE_IMPORT__

@Component({
  selector: 'size-app',
  standalone: true,
  template: 'size harness',
})
class SizeApp {}

bootstrapApplication(SizeApp, { providers: [provideZonelessChangeDetection()] }).catch((err) =>
  console.error(err)
);
