#!/bin/bash
# Builds the Zig TS→fMP4 transmuxer to wasm and embeds it as a base64 TS module.
# Requires zig >= 0.16. The generated transmux-wasm.ts is committed so
# consumers never need the Zig toolchain.
set -euo pipefail
cd "$(dirname "$0")/.."

TRANSMUX_DIR=projects/ship-ui/ship-video/engine/transmux

(cd "$TRANSMUX_DIR/zig" && zig build-exe transmux.zig \
  -target wasm32-freestanding -O ReleaseSmall -fno-entry -rdynamic \
  -femit-bin=transmux.wasm)

node -e "
const { readFileSync, writeFileSync } = require('fs');
const wasm = readFileSync('$TRANSMUX_DIR/zig/transmux.wasm');
const b64 = wasm.toString('base64');
const lines = b64.match(/.{1,120}/g).join(\"' +\n  '\");
writeFileSync(
  '$TRANSMUX_DIR/transmux-wasm.ts',
  '// Generated by scripts/build-transmux.sh — do not edit by hand.\n' +
  '// Source: zig/transmux.zig (' + wasm.byteLength + ' bytes of wasm).\n' +
  \"export const TRANSMUX_WASM_BASE64 =\n  '\" + lines + \"';\n\"
);
console.log('transmux-wasm.ts generated (' + wasm.byteLength + ' bytes wasm)');
"
